version: '3'
services:
  web:
    image: jakubboucek/lamp-devstack-php:debug
    environment:
      APP_DEBUG: 1
      TZ: Europe/Stockholm
      PHP_IDE_CONFIG: "serverName=docker-cli"
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    ports:
      - "127.0.0.1:8080:80"
    restart: always
    volumes:
      - ".:/var/www/html"

  mysqldb:
    image: jakubboucek/lamp-devstack-mysql
    environment:
      MARIADB_DATABASE: vcs
      MARIADB_ROOT_PASSWORD: revachol
      TZ: Europe/Stockholm
    ports:
      - "127.0.0.1:33060:3306"
    restart: always
    volumes:
      - "./.docker/mysql/data:/var/lib/mysql"